services:

  make:
    image: keystone-make:${MD5_MAKE}
    build:
      context: ./dev/docker/make
      dockerfile: Dockerfile
    volumes:
      - ${HOST_PROJECT_PATH}:/app

  nodejs:
    image: keystone-nodejs:${MD5_NODEJS}
    build:
      context: ./dev/docker/nodejs
      dockerfile: Dockerfile
    volumes:
      - ${HOST_PROJECT_PATH}:/app
    ports:
      - "3000:3000"
    environment:
      HOST: "0.0.0.0"

